/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <android/log.h>
#include <android/bitmap.h>
#include <string.h>
#include <fcntl.h>

/* Header for class org_secmem_amsserver_FBController */

#ifndef _Included_org_secmem_amsserver_FBController
#define _Included_org_secmem_amsserver_FBController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_secmem_amsserver_FBController
 * Method:    openFrameBuffer
 * Signature: (I)V
 */
JNIEXPORT int JNICALL Java_org_secmem_amsserver_FBController_openFrameBuffer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_secmem_amsserver_FBController
 * Method:    setBitmap
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_secmem_amsserver_FBController_setBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_secmem_amsserver_FBController
 * Method:    closeFrameBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_secmem_amsserver_FBControllerr_closeFrameBuffer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
